### ISSUE TITLE
[BUG]: fetch twice with React.StrictMode

### ISSUE THREAD

**Issue by hyoban** [jotaijs/jotai-cache#5]
![ScreenShot 2024-01-06 21 04 18](https://github.com/jotaijs/jotai-cache/assets/38493346/650bf32c-0995-415d-9a50-6014e6d8d2c6)

https://codesandbox.io/p/sandbox/suspicious-archimedes-t8qhly

**Comment by dai-shi** [comment]
Interesting. It looks worse than the normal atom.

I wasn't able to reproduce the behavior with https://codesandbox.io/p/sandbox/suspicious-archimedes-t8qhly 😕

**Comment by hyoban** [comment]
Maybe try manually adding `<React.StrictMode><App /></React.StrictMode>` to the example at https://jotai.org/docs/extensions/cache .


https://github.com/jotaijs/jotai-cache/assets/38493346/6143d4dc-e65e-412f-a832-32a45acc2ea4

**Comment by dai-shi** [comment]
Oh, I see. It happens for the first time only. Now I see it with https://codesandbox.io/p/sandbox/suspicious-archimedes-t8qhly.

So, do you have any idea how this is causing?

**Comment by hyoban** [comment]
My understanding is this, but not sure. Under StrictMode, the component will be rendered twice.

1. the Promise requested for the first time is added to the cache.
2. When the component is rendered for the second time, because `writeGetter` is ready after `onMount`, the second requested Promise is also recorded in the cache.
3. After the first request gets the result, the data used in the second rendering is the result of the first request.
4. In the second request, the component switches to loading again. After getting the result, the result of the second request is displayed.

An incorrect method that can make the display effect correct is to replace `cache.unshift` with `cache.push`, so that the Promise of the first request is always used.

**Comment by dai-shi** [comment]
> because writeGetter is ready after onMount

Oh, that's it. I forgot about it. Good catch.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/jotai-cache/v/0.4.0
