### ISSUE TITLE
read function now have to be async

### ISSUE THREAD

**Issue by hyoban** [jotaijs/jotai-cache#9]
```
setSelf function cannot be called in sync
```

**Comment by dai-shi** [comment]
Ooooops, I didn't notice it. Hmm, how should I fix it? We could only allow async read... 🤔 
Thanks for reporting!

**Comment by hyoban** [comment]
To be honest, I don’t know how to deal with it.🫣 hhhh.

Now, I can only use jotai with tanstack query, but it provides functionality that may not always be needed. And I need to specify the query key manually.

**Comment by surgit** [comment]
Hasn't been published to npm yet?

**Comment by dai-shi** [comment]
I was hoping to get some feedbacks. Let's ship it anyways.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/jotai-cache/v/0.4.1

**Comment by eranimo** [comment]
Why does it always have to be async? Seems like we may need two atoms...

**Comment by dai-shi** [comment]
It's the way how it works now.
Can you show some code snippets to explain needing two atoms?
